# Generated by Django 5.1.1 on 2024-10-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
